steps:
- id: 'build-tag'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia.gcr.io/$PROJECT_ID/janus:$SHORT_SHA','-f', 'Dockerfile.multi-stage', '.']
- id: 'push'
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia.gcr.io/$PROJECT_ID/janus:$SHORT_SHA']
