FROM golang:1.12.5-alpine3.9 as builder

RUN apk update && apk upgrade && apk add --no-cache alpine-sdk

RUN mkdir /go-app
WORKDIR /go-app
COPY go.mod .
COPY go.sum .

RUN go mod download
COPY . .

RUN CGO_ENABLED=0 go build -o janus cmd/janus/*.go
# -----------------------------------------------------------------------------
FROM quay.io/prometheus/busybox:latest
LABEL maintainer="gavin.zhou@gmail.com"

COPY --from=builder /go-app/janus /bin/janus

ENTRYPOINT ["/bin/janus"]
